# -*- coding: utf-8 -*-
"""Exp10_foml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BSK-oKqov-JStE70S4bSxcZDRPNzO4bL
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.decomposition import PCA

# Step 1: Load the Breast Cancer dataset
cancer = load_breast_cancer()
X = cancer.data  # Features (30 features about cell nuclei)
y = cancer.target  # Labels (Malignant: 1, Benign: 0)

# Step 2: Apply PCA for dimensionality reduction (reduce to 2 dimensions)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

# Step 3: Plot the reduced data (2D)
plt.figure(figsize=(8, 6))
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y, cmap='viridis', alpha=0.6)
plt.colorbar(scatter, label='Tumor Type (0: Benign, 1: Malignant)')
plt.title('PCA on Breast Cancer Dataset (2D)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True)
plt.tight_layout()
plt.show()

# Step 4: Explained variance ratio (optional but insightful!)
explained_variance = pca.explained_variance_ratio_
print(f"Explained variance ratio for the 2 components: {explained_variance}")
print(f"Total variance captured by 2 components: {np.sum(explained_variance):.2%}")

